spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8080
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1 #???????????
server:
  port: 8080